# Generated by Django 4.2.2 on 2023-06-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('state', models.CharField(choices=[('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Nagaland', 'Nagaland'), ('Mizoram', 'Mizoram'), ('Uttarakhand', 'Uttarakhand'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Telangana', 'Telangana'), ('Tamil Nadu', 'Tamil Nadu'), ('Rajasthan', 'Rajasthan'), ('Punjab', 'Punjab'), ('Goa', 'Goa'), ('Chhattisgarh', 'Chhattisgarh'), ('Bihar', 'Bihar'), ('Puducherry', 'Puducherry'), ('Lakshadweep', 'Lakshadweep'), ('Ladakh ', 'Ladakh '), ('New Delhi ', 'New Delhi '), ('Daman and Diu', 'Daman and Diu'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Raipur', 'Raipur'), ('Bhali', 'Bhali')], max_length=50)),
                ('gender', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('pImage', models.ImageField(blank=True, upload_to='pimages')),
                ('rdoc', models.FileField(blank=True, upload_to='rdocs')),
            ],
        ),
    ]
